# Generated by Django 4.2.2 on 2023-06-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackageexclusion',
            options={'verbose_name_plural': 'Tour Package Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='tourpackageimage',
            options={'verbose_name_plural': 'Tour Package Images'},
        ),
        migrations.AlterModelOptions(
            name='tourpackageinclusion',
            options={'verbose_name_plural': 'Tour Package Inclusions'},
        ),
    ]
