# Generated by Django 4.2.2 on 2023-06-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tourpackage_description_alter_tourpackage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
