# Generated by Django 4.2.2 on 2023-06-15 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_touravailabledates_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
