# Generated by Django 4.2.2 on 2023-06-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tourpackage_age_alter_tourpackage_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='start_date',
        ),
    ]
