# Generated by Django 4.2.2 on 2023-06-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='street_address',
        ),
    ]
