# Generated by Django 4.2.2 on 2023-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_booking_city_remove_booking_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dates',
        ),
        migrations.AlterField(
            model_name='booking',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dates',
            field=models.ManyToManyField(to='app.touravailabledates'),
        ),
    ]
